name: real_amis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  app_links: ^6.4.1
  dartz: ^0.10.1
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.1
  fpdart: ^1.1.1
  get_it: ^9.0.5
  hive: ^4.0.0-dev.2
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.0
  internet_connection_checker_plus: ^2.9.0
  intl: ^0.20.2
  isar_flutter_libs: 
  path_provider: ^2.1.5
  supabase_flutter: ^2.10.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 300